export enum EnvVariable {
  NODE_ENV = 'NODE_ENV',
  MONGODB_URI = 'MONGODB_URI',
  TCP_PORT = 'TCP_PORT',
  S3_REGION = 'S3_REGION',
  S3_ACCESS_KEY_ID = 'S3_ACCESS_KEY_ID',
  S3_SECRET_ACCESS_KEY = 'S3_SECRET_ACCESS_KEY',
  S3_BUCKET = 'S3_BUCKET',
  S3_BUCKET_FOLDER = 'S3_BUCKET_FOLDER',
}
